version: '3'

services:
  application2:
    build: application2/
    restart: always
    ports:
      - "5000:5000"
    networks:
      vpn:
        ipv4_address: 172.20.0.2
    volumes:
      - "./application2/DB.db:/usr/src/app/DB.db"
    environment:
      - TZ=Europe/Moscow

  application:
    build: application/
    restart: always
    ports:
      - "8080:8080"
    networks:
      vpn:
        ipv4_address: 172.20.0.3
    environment:
      - TZ=Europe/Moscow
      - ContainerApp2=172.20.0.2:5000

networks:
  vpn:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/16
